spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password:  ${DB_PASSWORD}
    driver-classname: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
required:
  age:
    required-age: 18