spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clear-solutions-db
    username: postgres
    password: postgres
    driver-classname: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
